import React from "react";

import batteryPhoto1 from "../../assets/images/batteryphoto1.png";
import batteryPhoto2 from "../../assets/images/batteryphoto2.png";

import "../../assets/styles/ProjectPages.scss";


const BatteryEnclosureProject = {


    Title: () => (

        <>
            Electric Vehicle Automated Battery Enclosure
        </>

    ),





    Content: () => (

        <div className="project-content battery-project">



            {/* OVERVIEW */}

            <section className="project-section">

                <h2>
                    Overview
                </h2>


                <p>

                    This project involved designing an automated battery enclosure system for Queen's Relectric, a student engineering team focused on converting gasoline vehicles into electric vehicles.

                    <br/><br/>

                    The goal was to develop a modular enclosure capable of protecting lithium iron phosphate (LiFePO₄) battery cells while maintaining safe operating temperatures through an active cooling system.

                    <br/><br/>

                    I contributed to the mechanical design, CAD modelling, thermal analysis, and system evaluation of the final enclosure design.

                </p>


            </section>







            {/* BACKGROUND */}

            <section className="project-section">


                <h2>
                    Background
                </h2>


                <p>

                    Electric vehicle battery packs require effective thermal management to maintain performance, safety, and battery lifetime. Queen's Relectric required a battery enclosure that could protect the battery cells while providing a reliable cooling solution.

                    <br/><br/>

                    Several thermal management approaches were evaluated, including passive cooling, active air cooling, and liquid cooling. An active air-cooling design was selected due to its balance of thermal performance, cost, manufacturability, and system complexity.

                </p>


            </section>







            {/* TECHNICAL DETAILS */}

            <section className="project-section">


                <h2>
                    Technical Details
                </h2>


                <p>

                    The final design incorporated a modular polycarbonate enclosure with an integrated active cooling system. Heat generated by the batteries was transferred through aluminum cold plates and heat pipes into a fin array, where forced convection from fans increased heat dissipation.

                </p>





                <ul className="battery-details-list">


                    <li>
                        SolidWorks modelling of a modular EV battery enclosure
                    </li>


                    <li>
                        Thermal simulation used to evaluate temperature distribution throughout the system
                    </li>


                    <li>
                        Active cooling system using cold plates, heat pipes, heat fins, and PWM-controlled fans
                    </li>


                    <li>
                        Arduino-based temperature monitoring and fan control system
                    </li>


                    <li>
                        Designed for scalability from a 4-cell prototype to a 16-cell battery pack
                    </li>


                    <li>
                        Considered manufacturability, electrical insulation, ventilation, and maintenance accessibility
                    </li>


                </ul>






                {/* MAIN IMAGE */}

                <div className="battery-image-container">


                    <img

                        src={batteryPhoto1}

                        alt="Battery enclosure final design"

                    />


                    <p className="image-caption">

                        Final design of the full enclosure system. The system consists of three primary components: a battery bracket secured within the casing, a ventilated enclosure allowing airflow throughout the system, and a removable lid providing protection while maintaining access for cable routing.

                    </p>


                </div>


            </section>









            {/* CHALLENGES */}

            <section className="project-section">


                <h2>
                    Challenges
                </h2>


                <p>

                    The primary challenge was balancing thermal performance, size constraints, cost, and manufacturability within the project limitations.

                    <br/><br/>

                    Multiple cooling concepts were evaluated before selecting an active air-cooling approach. Additional modelling and simulation were required to validate the thermal performance of the final design.

                </p>


            </section>









            {/* RESULTS */}

            <section className="project-section">


                <h2>
                    Results
                </h2>


                <p>

                    The project resulted in a complete CAD design and thermal evaluation of a modular EV battery enclosure.

                    <br/><br/>

                    SolidWorks thermal simulations demonstrated effective heat transfer through the heat plates, heat pipes, and heat fins, validating the proposed cooling approach.

                </p>






                <div className="battery-simulation-image">


                    <img

                        src={batteryPhoto2}

                        alt="SOLIDWORKS thermal simulation results"

                    />


                    <p className="image-caption">

                        SolidWorks thermal simulation results showing temperature distribution throughout the cooling system. Heat accumulates at the cold plates, while the heat fins maintain lower temperatures due to forced convection.

                    </p>


                </div>


            </section>





        </div>

    )


};


export default BatteryEnclosureProject;